name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Run Go Build
        run: go build main.go